import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const createPostMutation = api.post.createPost.useMutation();
  const [text, setText] = useState<string>("");

  const { data: posts } = api.post.getAllPosts.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-100">
        <h1 className="text-4xl">Create a post</h1>
        <form
          className="mt-12 flex flex-col items-center justify-center space-y-4"
          onSubmit={(e) => {
            e.preventDefault();
            createPostMutation.mutate({ text });
          }}
        >
          <input
            type="text"
            className="rounded-md border-2 p-2"
            value={text}
            onChange={(e) => setText(e.target.value)}
          />
          <button
            type="submit"
            className="mt-4 rounded-md bg-blue-500 p-2 text-white"
          >
            Submit
          </button>
        </form>
        <div className="mt-12">
          <h2 className="text-4xl">Posts</h2>
          <ul className="mt-4 space-y-4">
            {posts?.map((post) => (
              <li key={post.id}>
                <p>{post.text}</p>
              </li>
            ))}
          </ul>
        </div>
      </main>
    </>
  );
};

export default Home;
